#配置数据库连接信息
spring:
  application:
    name: Tlias-Web-Management

  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: Qinwenbin2005.
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true